version: '3.8'

services:
  nginx:
    image: nginx:1.19.3
    restart: always
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - digital-stage
  mongo:
    image: mongo:4.2.10
    restart: always
    volumes:
      - ./data/db:/data/db
    networks:
      - digital-stage

  server:
    image: server:0.0.1
    build: ./server
    init: true
    depends_on:
      - mongo
      - auth
    restart: always
    environment:
      MONGO_URL: 'mongodb://mongo:27017'
      MONGO_DB: 'digitalstage'
      AUTH_URL: 'http://auth:5000'
      PORT: '4000'
    networks:
      - digital-stage

  auth:
    image: auth:0.0.1
    build: ./auth-server
    init: true
    depends_on:
      - mongo
    restart: always
    environment:
      MONGO_URL: 'mongodb://mongo:27017'
      MONGO_DB: 'digitalstage'
      PORT: '5000'
    networks:
      - digital-stage

  router-distributor:
    image: router-distributor:0.0.1
    build: ./router-distributor
    init: true
    depends_on:
      - auth
      - server
    restart: always
    environment:
      MONGO_URL: 'mongodb://mongo:27017'
      MONGO_DB: 'digitalstage'
      AUTH_URL: 'http://auth:5000'
      API_URL: 'http://server:4000'
      PORT: '4020'
    networks:
      - digital-stage

  router:
    image: router:0.0.1
    build: ./router
    init: true
    depends_on:
      - router-distributor
    restart: always
    environment:
      DOMAIN: 'localhost'
      AUTH_URL: 'http://auth:5000'
      RTC_MIN_PORT: '40000'
      RTC_MAX_PORT: '40100'
      ROUTER_DIST_URL: 'http://router-distributor:4020'
      API_URL: 'http://server:4000'
      EMAIL: 'test@test.tld'
      PASSWORD: 'Testtest@123'
      PORT: '8080'
      IP: '0.0.0.0'
    networks:
      - digital-stage

  webclient:
    image: webclient:0.0.1
    build: ./webclient-1
    init: true
    depends_on:
      - auth
      - server
      - router-distributor
    restart: always
    environment:
      NEXT_PUBLIC_AUTH_URL: '/auth'
      NEXT_PUBLIC_ROUTER_DIST_URL: '/routerdist'
      NEXT_PUBLIC_ROUTERS_URL: '/routerdist'
      NEXT_PUBLIC_API_URL: 'http://localhost:4000'
      PORT: '3000'
    networks:
      - digital-stage

networks:
  digital-stage:
